"""Repository root discovery for commands launched inside a project tree."""

from pathlib import Path

from bytely.graph.write import GRAPH_FILE


def find_bytely_root(start: str | Path) -> Path | None:
    """Return the nearest ancestor with a generated Bytely graph, if present."""
    start_path = Path(start).resolve()
    current = start_path if start_path.is_dir() else start_path.parent
    for candidate in (current, *current.parents):
        if (candidate / "bytely" / GRAPH_FILE).is_file():
            return candidate
    return None
